name: hello-world

profiles:
  1-4-0:
    endpoint: /hello/
    max_memory: 0.5G
    max_cpu: 0.5
  1-5-0:
    endpoint: /hello/
    max_memory: 0.5G
    max_cpu: 0.5
    weight: 30
  default:
    name: {{branch.replace('/', '-')}}
    endpoint: /preview/hello/{{branch}}/
    max_memory: 0.25G
    max_cpu: 0.25
